-- MySQL Script generated by MySQL Workbench
-- Sat Jan  9 13:46:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerce_db` ;

-- -----------------------------------------------------
-- Table `ecommerce_db`.`clink_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`clink_address` (
  `clink_id` BIGINT NOT NULL AUTO_INCREMENT,
  `clink_address` VARCHAR(255) NULL DEFAULT NULL,
  `doctor_id` BIGINT NULL DEFAULT NULL,
  `clink_latitude` DOUBLE NULL DEFAULT NULL,
  `clink_longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`clink_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`doctor_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`doctor_info` (
  `doctor_id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `fees` DOUBLE NULL DEFAULT NULL,
  `hospital_id` BIGINT NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `mobile` VARCHAR(255) NULL DEFAULT NULL,
  `speciality` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`doctor_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`employee` (
  `id` INT NOT NULL,
  `empName` VARCHAR(45) NULL DEFAULT NULL,
  `empSuber` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`employees` (
  `idemployee` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `salary` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idemployee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`hospital_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`hospital_address` (
  `hospital_id` BIGINT NOT NULL AUTO_INCREMENT,
  `hospital_address` VARCHAR(255) NULL DEFAULT NULL,
  `hospital_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`hospital_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`sm_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`sm_lookup` (
  `recid` BIGINT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `is_dismantle` INT NULL DEFAULT NULL,
  `lookup_type` VARCHAR(255) NULL DEFAULT NULL,
  `lookup_value` VARCHAR(255) NULL DEFAULT NULL,
  `parent_lookup` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`recid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`user_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`user_information` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `mobile` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
