package com.Project.Ecommerce.Constants;

public interface CodesAndKeys {


	String ENTITY_NOT_FOUND_CODE = "999001";
	String ENTITY_NOT_FOUND_KEY = "ENTITY_NOT_FOUND_KEY";
	String INTERNAL_SERVER_ERROR_CODE = "999002";
	String INTERNAL_SERVER_ERROR_KEY = "INTERNAL_SERVER_ERROR_KEY";
	String CAN_NOT_CREATE_ENTITY_CODE = "999003";
	String CAN_NOT_CREATE_ENTITY_KEY = "CAN_NOT_CREATE_ENTITY_KEY";
	String CAN_NOT_UPDATE_ENTITY_CODE = "999004";
	String CAN_NOT_UPDATE_ENTITY_KEY = "CAN_NOT_UPDATE_ENTITY_KEY";
	String CAN_NOT_DELETE_ENTITY_CODE = "999005";
	String CAN_NOT_DELETE_ENTITY_KEY = "CAN_NOT_DELETE_ENTITY_KEY";
	String PERMAISSION_VALIDATION_USER_NOT_ALLOWED_CODE = "999006";
	String PERMAISSION_VALIDATION_USER_NOT_ALLOWED_KEY = "PERMAISSION_VALIDATION_USER_NOT_ALLOWED_KEY";
	String USER_ID_NOT_FOUND_CODE = "999007";
	String USER_ID_NOT_FOUND_KEY = "USER_ID_NOT_FOUND_KEY";
	String USER_NAME_NOT_FOUND_CODE = "999008";
	String USER_NAME_NOT_FOUND_KEY = "USER_NAME_NOT_FOUND_KEY";
	String ORGANIZATION_ID_NOT_FOUND_CODE = "999009";
	String ORGANIZATION_ID_NOT_FOUND_KEY = "ORGANIZATION_ID_NOT_FOUND_KEY";
	String SESSION_ID_NOT_FOUND_CODE = "999010";
	String SESSION_ID_NOT_FOUND_KEY = "SESSION_ID_NOT_FOUND_KEY";
	String USER_ID_IS_NOT_NUMBER_CODE = "999011";
	String USER_ID_IS_NOT_NUMBER_KEY = "USER_ID_IS_NOT_NUMBER_KEY";
	String ORGANIZATION_ID_IS_NOT_NUMBER_CODE = "999012";
	String ORGANIZATION_ID_IS_NOT_NUMBER_KEY = "ORGANIZATION_ID_IS_NOT_NUMBER_KEY";

	String INVALID_ENTITY_ID_CODE = "999013";
	String INVALID_ENTITY_ID_KEY = "INVALID_ENTITY_ID_KEY";

	String LOG_REPOSITORY_INSTANCE_DOES_NOT_EXIST_CODE = "999014";
	String LOG_REPOSITORY_INSTANCE_DOES_NOT_EXIST_KEY = "LOG_REPOSITORY_INSTANCE_DOES_NOT_EXIST_KEY";
	
}
